### ISSUE TITLE
cannot run the website with npm

### ISSUE THREAD

**Issue by xarthurx** [NvChad/nvchad.github.io#172]
Hello, I'm trying to run the website locally to see if I can contribute with the code.

However, after cloning the repo and run:
```
npm install
npm run start
```
I got this error:

```
> nvchad website@0.4.1 start
> solid-start start

 solid-start start
 version  0.2.26
 adapter  static


  ➜  Page Routes:
     ┌─ http://localhost:3000/
     ├─ http://localhost:3000/themes
     ├─ http://localhost:3000/*404
     ├─ http://localhost:3000/docs/api
     ├─ http://localhost:3000/docs/contribute
     ├─ http://localhost:3000/docs/credits
     ├─ http://localhost:3000/docs/debugging-config
     ├─ http://localhost:3000/docs/features
     ├─ http://localhost:3000/news/
     ├─ http://localhost:3000/docs/config/format_lint
     ├─ http://localhost:3000/docs/config/lsp
     ├─ http://localhost:3000/docs/config/mappings
     ├─ http://localhost:3000/docs/config/nvchad_ui
     ├─ http://localhost:3000/docs/config/plugins
     ├─ http://localhost:3000/docs/config/snippets
     ├─ http://localhost:3000/docs/config/syntax
     ├─ http://localhost:3000/docs/config/theming
     ├─ http://localhost:3000/docs/config/walkthrough
     ├─ http://localhost:3000/docs/quickstart/install
     ├─ http://localhost:3000/docs/quickstart/learn-lua
     ├─ http://localhost:3000/docs/quickstart/post-install
     ├─ http://localhost:3000/news/v2.0
     └─ http://localhost:3000/news/v2.0_migration

  ➜  API Routes:
     None! 👻

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn npx ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npx',
  path: 'npx',
  spawnargs: [ 'serve', './dist/public' ]
}

Node.js v18.17.0
```

OS: Windows 11.

**Comment by siduck** [comment]
![image](https://github.com/NvChad/nvchad.github.io/assets/59060246/094e40dc-040a-4e6b-9b6e-b3349cb0c3fa)


npm run dev* , npm run start is just for testing the production build

**Comment by xarthurx** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/259766829-094e40dc-040a-4e6b-9b6e-b3349cb0c3fa.png)
> 
> npm run dev* , npm run start is just for testing the production build

`dev` runs fine, so I don't need to make sure the `start` runs OK?
Is this a `solid-start` bug?

**Comment by siduck** [comment]
@xarthurx start is only used if you want to test production build, it will not work  until you run the build command

**Comment by xarthurx** [comment]
> @xarthurx start is only used if you want to test production build, it will not work until you run the build command

I run build already.
The error is produced after I can build the site successfully.

**Comment by siduck** [comment]
can reproduce this, seems like the build command has an issue. i removed the "mv* command related stuff and it works now, need to verify why i had that stuff in the first place!

**Comment by xarthurx** [comment]
FYI, the windows issue is a bug for `solid-start` and has been fixed:
https://github.com/solidjs/solid-start/issues/986

**Comment by siduck** [comment]
@xarthurx oh! but i'm still unable to run the production build locally, i get this error

![image](https://github.com/NvChad/nvchad.github.io/assets/59060246/440012ba-5d21-4723-8e61-a0b2b2678618)

**Comment by xarthurx** [comment]
> @xarthurx oh! but i'm still unable to run the production build locally, i get this error
> 
> ![image](https://user-images.githubusercontent.com/59060246/259947241-440012ba-5d21-4723-8e61-a0b2b2678618.png)

With your original build settings?
It is two separate issue:
- The Windows issue prevents me to `npm start`, but it works on WSL.
- This 404 issue is caused by your `build` script, probably the `mv` thing. I guess it is either caused by some solid-start bug or something in your code. If it is a bug, probably solid-start only checks `dist/public`...

**Comment by xarthurx** [comment]
> @xarthurx if i remove mv stuff, build works locally but the deployed site shows 404 . and if i add the mv stuff, the deployed site works but local build preview shows 404 :(

Probably report this to `solid-start`? After communicating with their developer, and reading their docs, I think the `solid-start` is still not a stable product, not to say `solid-start-static` is very experimental...

**Comment by xarthurx** [comment]
> i remove mv stuff, build works locally but the deployed site shows 404 . and if i add the mv stuff, the deployed site works but local build preview shows 404 :(

A temporary solution might be to create two npm commands: `build` and `buildForDeploy`?

**Comment by siduck** [comment]
> > i remove mv stuff, build works locally but the deployed site shows 404 . and if i add the mv stuff, the deployed site works but local build preview shows 404 :(
> 
> A temporary solution might be to create two npm commands: `build` and `buildForDeploy`?

sounds good, what would be the ideal solution? @ryansolid
